language: java
jdk:
- oraclejdk8
dist: trusty
install: true
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=API4KBs_kmdp-standard-models-impl -Ppublic -q
deploy:
  provider: script
  script: mvn deploy -DskipTests -Ppublic -q -s .travis.settings.xml
  skip_cleanup: true

addons:
  sonarcloud:
    organization: "api4kbs"
    token:
      secure: "P3AcXHM1YNkpC8kxIcN8+o7Lntr9+qzDLkWIUXpJgLseQRzc8A/7U5JYlX/oBNIXtNkaSXhujLqqgWKWKlWJV3nQtn9kTq6HUuYdCtYbGwS3mTo3YubsADhhAiU/HQ46hC6kdeFpwIsSZ/Ba78LfF19kSo81POy6ov3Id19rZ9gx9SjFxfp/nqF670I6AO8E9f0SMlBMOXszTc5fJWQZQoQSQacdD1AkRFTKEQX+zW2921c709mW0l0qm8vLhZLzIggT/W6m6XlcOi9Vib0gfmhzmM9Pnkcgk7bkN56hxHEU0zQgKAguMP5Ojs93DPnjKv3Zn2GmM6Wqj7VdW/MZ+DDO6fKCb0HjxjxF+R4L6Ivxv6OdBNXdQ7QLEBhpdO47yTB+Exa+WBGpHveQ4JoX79M1v+9X6/y044n7XAWFzPn9EU8hJU3fj1vv1RPQXVqEBIAIM9F1CxO+BU5ahfIFl6NdOLwLlPO9lRo/HvUzos/1CoZgX7aeyAF+izyVLCAAOxzQx36cg+6E2/kWCvMnXSzMN0jRrdqIL6ZWlIodXjaZ3l/CAuPqkTJkeA0l7ZN0CPOP8io8NK2v15/GIP8rDh8o4ub4F6rqrxheZuQbLfpd5C0RgsriaSu9OrZTTInLAXw6mP2M2FB1LILosMnPm2IrEfRw2Hz53RHLClT22yI="

env:
  global:
  - secure: LSzc6+3+GMZEguIC+NZJ/olY1UK7ciykaC/w1zWfW4nWs2/1Iea2SnkI120e2d0pOIg9a+FGVvXHSBytS/moY3fnm1t8SO0SWzBXW0w3ehQOJn3iRSnbpXC2HISIk2mZCxHTwKJXzwSL7LcronUjmSgLh8BcdNTxbCF4mdlbG2h5WX/XLR2Q+FxTYcdUn9Tdes3X1GtB8Xvy+sgvRMOX9t03HyNN+60P8ES5yf3RI3gfBXVWNnXh9DZvOw1lGRSwTg7+3tUnThjhPNRNHIK20RrQJ09EeGp85xgl/3eZkiZxXCqks9P+oiCrWquNaiZUvY7az/UtIFcuxERsPRh1GF4Hwl+931TG+L2WTq2b222ta0JygFU94X33S4D9gIWg0M3++7aq3gEoVDYm0c5/nXAacIPLtZxbDfm0SJNXjhuTfxwVYKJnfH+0j8akAQVw0TROrDvt1Xj43oQL+472dq1PDd6ByUgzT94tvamx9ybB9hrl32d1EapmGo1kr5IVwaPsJtTkf9Tisx5T/NPfhAjoB6dMMW6dhQGi/zOgXnfQa/KXHD97HV0nDzy8v86FXy3//6BwZhwynXnjINSJiU+kgDa2AohVUiSlePlaEp+jJxxFscucPwLcsV/AfneVCrV3P952+0tdjFcIMc9Cq6bEgTaWp3Zp8WQVZS59xSo=
  - secure: tZyP/9mIHO+HA0nEL6M86jiMlLTceVTc6TjAUhZkRtz9rDy/0RKFn5OwYKo4Hyzrb1oolYThq3HUlF++wg87XKjQVIj8gNfNkDFCZxTcjPm7AiGw4qFPnjti2yVyLBSQPqqdI0jwn65IWbAY72Nik0G1jStUZkm25FDF/zM2m51kDs5wTEo1+FD15MbQbkGfR96s1LW4hvzmfJQQWNh0hIQGkSdsXV7nBFFwy5ok24chAxDdEBS4c9FQrqvZ4z7w3gHv4Wb0I/LL0J2Z8o85/nGk1/kb3zPAf6Cvq2Mn/wxZPu5hSGZINQOTI/VGeApPODkl91bE9yRPFtllCcsG7cFjbljHAiOIZ4zDvl+bsTlcsKB8sMpNeaxPzr+Uwib8nNJKzOcH9ZDtYGdl4GFKDiogOzJkPdftdYEZHTFeHvrkko+EDFTISKgsif6LyP3rT0UcXYYRY5bpSo1U5zgquj4OKuYbowhwXAIfLJdHaqI0PEAJAaBS/v3y7a6SWuHuYf4I6grgenFtmXpIu1rgKhgT6DFC0r/Xv5s9wl2yNCbQQEQKDGXPi1l2Q9E90MYHxKMWueQRPtbyM8EdvMiKN/tvnjoWByWoenzQGkK8zv++G6HNV5ih1DhfYuL60GaGqSt1j6IzbPxpheUqTUNyc8CIhXCCP/xUfRZ+1kKtix8=
