swagger: '2.0'

info:
  version: "1.0.0"
  title: 'KMDP Endpoint Monitoring API'
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Reusable module that can be implemented for Java products using Spring to consolidate like code and surface the health endpoints (health, state, version) within any Java Spring implementation.
tags:
  - name: Health
    description: |
      Return information about the application including schema version, status, system, version, environment, and components.

  - name: Version
    description: |
      Return the version of the application.

  - name: State
    description: |
      Return the state of the application including schema version, environment, and features.

produces:
  - application/json

paths:

  ####################################################################################################
  # Health
  ####################################################################################################

  /health:
    get:
      tags:
        - Health
      summary: Display the health of the application.
      description: |
        Return information about the application including schema version, status, system, version, environment, and components.
      operationId: getHealthData
      produces:
        - application/json
      responses:
        200:
          description: |
            A list of application information detailing the status of the system.
          schema:
            $ref: '#/definitions/HealthData'
        500:
          description: |
            Unable to determine the health of the application.
        501:
          description: |
            This endpoint has not been implemented for this application.

  ####################################################################################################
  # Version
  ####################################################################################################

  /version:
    get:
      tags:
        - Version
      summary: Display the version of the application.
      description: |
        Return the version of the application
      operationId: getVersionData
      produces:
        - application/json
      responses:
        200:
          description: |
            The version of the application
          schema:
            type: string
        500:
          description: |
            Unable to determine the version of the application.
        501:
          description: |
            This endpoint has not been implemented for this application.

  ####################################################################################################
  # State
  ####################################################################################################

  /state:
    get:
      tags:
        - State
      summary: Display the state of the application.
      description: |
        Return information about the application state
      operationId: getStateData
      produces:
        - application/json
      responses:
        200:
          description: |
            A list of application information detailing the state of the system.
          schema:
            $ref: '#/definitions/StateData'
        500:
          description: |
            Unable to determine the state of the application.
        501:
          description: |
            This endpoint has not been implemented for this application.

####################################################################################################

definitions:

  HealthData:
    description: The health endpoint schema
    type: object
    allOf:
      - properties:
          schemaInfo:
            $ref: '#/definitions/SchemaMetaInfo'
          at:
            type: string
      - $ref: '#/definitions/DeployedApplication'

  StateData:
    description: The state endpoint schema
    type: object
    properties:
      schemaInfo:
        $ref: '#/definitions/SchemaMetaInfo'
      serviceNowReference:
        $ref: '#/definitions/ServiceNowInfo'
      buildConfiguration:
        $ref: '#/definitions/BuildInfo'
      deploymentEnvironmentConfiguration:
        $ref: '#/definitions/MiscProperties'
      features:
        $ref: '#/definitions/Flags'


  CommonAppInfo:
    description: "Attributes common to Software Applications, and Components thereof"
    # discriminator: type
    properties:
      #  type:
      #    enum:
      #      - Software Application
      #      - Software Component
      serviceNowReference:
        $ref: '#/definitions/ServiceNowInfo'
      name:
        type: string
      version:
        type: string
      status:
        $ref: '#/definitions/Status'
      statusMessage:
        type: string
      components:
        type: array
        items:
          $ref: '#/definitions/ApplicationComponent'

  ApplicationComponent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonAppInfo'
      - type: object
        properties:
          details:
            $ref: '#/definitions/MiscProperties'

  DeployedApplication:
    type: object
    allOf:
      - $ref: '#/definitions/CommonAppInfo'
      - type: object
        properties:
          deploymentEnvironment:
            $ref: '#/definitions/DeploymentEnvironment'

  Status:
    description: The primary signal as to the health of the service or application.
    type: string
    enum:
      - Up
      - Impaired
      - Down

  ServiceNowInfo:
    type: object
    properties:
      id:
        pattern: CI*
        description: The ServiceNow configuration item ID
        type: string
      url:
        description: The ServiceNow configuration item URI
        type: string
      display:
        description: A human-readable display name for the system
        type: string

  BuildInfo:
    type: object
    properties:
      artifactName:
        type: string
      groupId:
        type: string
      artifactId:
        type: string
      version:
        type: string
      buildTime:
        type: string
      details:
          $ref: '#/definitions/MiscProperties'

  DeploymentEnvironment:
    description: The current application environment
    type: string
    enum:
      - dev
      - test
      - int
      - uat
      - local
      - prod
      - unknown

  MiscProperties:
    type: object
    additionalProperties:
      type: string

  Flags:
    type: object
    additionalProperties:
      type: boolean

  SchemaMetaInfo:
    type: object
    properties:
      url:
        type: string
      version:
        type: string
